#!/usr/bin/env bash

set -eu -o pipefail

. DISTINFO

SCRIPTDIR=`dirname $0`
TOPDIR=`realpath "$SCRIPTDIR"`

BASEURL=https://download.freebsd.org/ftp/releases/${ARCH}/${OSRELEASE}

pushd "${TOPDIR}" > /dev/null
  SUBDIR="distfiles";
  if [ ! -e "${SUBDIR}" ]; then
    mkdir -p "${SUBDIR}"
  fi
  pushd "${SUBDIR}" > /dev/null
    if [ ! -e "MANIFEST" ]; then
      curl -O "${BASEURL}/MANIFEST"
    fi
    for DISTFILE in $DISTFILES; do
      SHA256SUM=`awk "/^${DISTFILE}/ {print \\$2}" MANIFEST`
      if [ ! -e "${DISTFILE}" ]; then
        # download file if not exists
        curl -O "${BASEURL}/${DISTFILE}"
      elif [ "$SHA256SUM" != `openssl dgst -sha256 "${DISTFILE}" | awk '{print $2}'` ]; then
        # If there is a file, but has wrong SHA256 sum, we just re-download it
        rm ${DISTFILE}
        curl -O "${BASEURL}/${DISTFILE}"
      fi
      [ "$SHA256SUM" = `openssl dgst -sha256 "${DISTFILE}" | awk '{print $2}'` ]
    done
  popd > /dev/null
popd > /dev/null
